import type { Metadata } from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/provider";
import { TracingBeam } from "@/components/ui/tracing-beam";


const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Kentos DevPortfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
           <TracingBeam>{children}</TracingBeam>
        </ThemeProvider>
      </body>
    </html>
  );
}
